ALTER TABLE RECORD_WORKFLOW_TASK
  ADD COLUMN task_sequence BIGINT NULL AFTER id;

CREATE TEMPORARY TABLE RECORD_WORKFLOW_TASK_SEQUENCE_BACKFILL (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  task_sequence BIGINT NOT NULL
);

INSERT INTO RECORD_WORKFLOW_TASK_SEQUENCE_BACKFILL (id, task_sequence)
SELECT
  id,
  ROW_NUMBER() OVER (ORDER BY created_at ASC, updated_at ASC, id ASC)
FROM RECORD_WORKFLOW_TASK;

UPDATE RECORD_WORKFLOW_TASK AS task
JOIN RECORD_WORKFLOW_TASK_SEQUENCE_BACKFILL AS backfill ON backfill.id = task.id
SET task.task_sequence = backfill.task_sequence;

DROP TEMPORARY TABLE RECORD_WORKFLOW_TASK_SEQUENCE_BACKFILL;

ALTER TABLE RECORD_WORKFLOW_TASK
  MODIFY COLUMN task_sequence BIGINT NOT NULL,
  ADD UNIQUE KEY uq_record_workflow_task_sequence (task_sequence);

ALTER TABLE RECORD_WORKFLOW_TASK
  MODIFY COLUMN task_sequence BIGINT NOT NULL AUTO_INCREMENT;
